name: ui_countdown_timer
description: A UI countdown timer challenge.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/ui_countdown_timer
issue_tracker: https://github.com/cbonello/ui_countdown_timer/issues

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
